server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33061/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zjh520
  thymeleaf:
    prefix: classpath:/thymeleaf/
    suffix: .html
  Jpa:
    hibernate:
      # ????????
      ddl-auto: update
    # ??????sql
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
# mybatis????????sql???
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
